### ISSUE TITLE
releasing 0.1.0

### ISSUE THREAD

**Issue by ubnt-intrepid** [ubnt-intrepid/izanami#32]
- [ ] Finalize HTTP service abstraction
    - considers HTTP/1 or HTTP/2 upgrade and server push
- [ ] Basic Cookie management (#38)
- [ ] request-level local storage
    - Since `http::Extensions` needs the stored values satisfy `Send+Sync`, it is not suitable for using as a temporarily buffer during an request.
- [ ] (optional) HTTP/2 Server Push support
    - depends on `h2` crate
- [ ] (optional) HTTP/2 upgrade support
    - depends on `h2` crate
- [ ] (optional) switch to `tower-h2` or otherwise
- [x] (optional) wait for publishing `tokio-buf` on crates.io
    - remove `izanami-buf`
